version: '3.9'

services:

  main_bot:
    build:
      context: .
    env_file:
      - env/main.env
    restart: on-failure
    volumes:
      - ./app:/app
    depends_on:
      - postgres_main

  postgres_main:
    image: postgres:17-alpine
    env_file:
      - env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

    

