# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eventdb
    ports:
      - 5433:5432
    

